Test/ChatApp/urls.py
from django.urls import path
from . import views

#template tagging
app_name = 'ChatApp'

urlpatterns = [
    path('register', views.register, name="register"),
    path('index', views.index, name="index"),
    path('', views.home, name="home"),
    path('login', views.user_login, name="user_login"),
    path('logout', views.user_logout, name="user_logout"),
]

Test/Test/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ChatApp.urls'))
]

Test/ChatApp/forms.py
from django import forms
from django.contrib.auth.models import User
# from .models import UserProfileInfo


class form_user(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("username", "password", "password2", "email")

Test/ChatApp/views.py
from django.shortcuts import render
from .forms import form_user
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout


# Create your views here.


def register(request):
    registered = False
    if request.method == "POST":
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        user_form = form_user(data=request.POST)

        if password == password2:
            if user_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                registered = True

            else:
                print(user_form.errors)

        else:
            print("Password Mismatch")
            return HttpResponse("Password Mismatch")

    else:
        user_form = form_user()

    return render(request, 'ChatApp/registration.html',
                  {
                      'user_form': user_form,
                      'registered': registered,
                  })


def index(request):
    return render(request, 'ChatApp/index.html')


def home(request):
    return render(request, 'ChatApp/base.html')


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                # return HttpResponse("Login Successfull")
                return HttpResponseRedirect('index')
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print("Username: " + username + " Password: " + password)
            return HttpResponse("Invalid Login details")

    else:
        return render(request, 'ChatApp/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponse("User Logged Out")

Test/templates/ChatApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="CharApp/login.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container ">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'ChatApp:home' %}">ChatApplication</a></li>
            </ul>
            <ul class="nav navbar-nav">

                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'ChatApp:register' %}">Registration</a></li>

                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'ChatApp:user_logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'ChatApp:user_login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <div class="jumbotron"><h1 align="center">Chat Application</h1></div>
        {% endblock %}
    </div>

</body>
</html>

Test/templates/ChatApp/index.html
{% extends "ChatApp/base.html" %}

{% block body_block %}

<h1>Welcome {{ request.user.username }} </h1>

{% endblock %}

Test/templates/ChatApp/login.html
{% extends "ChatApp/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1 align="center">Login !! </h1>
    <form  action="{% url 'ChatApp:user_login' %}" method="POST">
        {% csrf_token %}
        <table align="center">
            <tr style="padding:10px; height:35px">
                <td><label for="username">Username:</label></td>
                <td><input type="text" name="username" placeholder="Enter Username"></td>
            </tr>
            <tr style="padding:10px; height:35px">
                <td><label for="password">Password:</label></td>
                <td><input type="password" name="password"></td>
            </tr>
        </table>
        <br>
        <div class="wrapper" style="text-align:center">
            <input type="submit" value="submit">
        </div>


    </form>

</div>

{% endblock %}

Test/templates/ChatApp/registration.html
{% extends "ChatApp/base.html" %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
        <h1>Thanks you for Registering</h1>
    {% else %}
        <h1 align="center">Register Here!</h1>
        <h3 align="center">Fill out the Form:</h3>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            <input class="btn-success" type="submit" value="Submit">
        </form>
    {% endif %}
</div>
{% endblock %}